on:
  workflow_call:
    inputs:
      package:
        required: true
        type: string
      files_to_ignore:
        required: false
        type: string
        default: ""

env:
  # Setting an environment variable with the value of a configuration variable
  package_folder: packages/${{ inputs.package }}
  FOUNDRY_PROFILE: ci

jobs:
  check:
    strategy:
      fail-fast: true

    name: Coverage
    runs-on: revolution_protocol_builds_ubuntu_large
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install node deps and foundry
        uses: ./.github/actions/setup_deps

      - name: Cache build
        uses: ./.github/actions/cache_foundry_build
        with:
          package_folder: packages/${{ inputs.package }}
          foundry_profile: coverage

      - name: Run Forge coverage
        if: github.ref == 'refs/heads/main'
        run: cd $package_folder && forge coverage --report lcov

      - name: Run Forge coverage with CI profile
        run: cd $package_folder && FOUNDRY_PROFILE=ci forge coverage --report lcov

      - name: Setup LCOV
        uses: hrishikesh-kadam/setup-lcov@v1

      - name: Filter files to ignore
        run: |
          cd ./${{ env.package_folder }} && lcov --rc lcov_branch_coverage=1 \
          --remove lcov.info \
          --output-file lcov.info "*node_modules*" "*test*" "*script*" ${{ inputs.files_to_ignore }}

      - name: Check if GITHUB_TOKEN is set
        run: |
          if [ -z "${{ secrets.GITHUB_TOKEN }}" ]; then
              echo "GITHUB_TOKEN is not set"
          else
              echo "GITHUB_TOKEN is set"
          fi

      - name: Report code coverage
        uses: zgosalvez/github-actions-report-lcov@v2
        with:
          coverage-files: ./${{ env.package_folder }}/lcov.info
          minimum-coverage: 85 # TODO update this once first audit pass goes through
          artifact-name: code-coverage-report
          github-token: ${{ secrets.GITHUB_TOKEN }}
          working-directory: ./${{ env.package_folder }}
